Nichtfunktionale Anforderungen zur Anwesenheitsliste ergänzt
ThorbenKonopka/Stundenplan pull request #50
Opened 2024-05-09 21:28 UTC by MasterMT9

Habe die Anforderungen inklusive Joshuas neuer Nummerierung ergänzt

2024-05-09 21:31 UTC, MasterMT9 commented
Wie kann ich den pull request zum Issue linken?

2024-05-11 07:18 UTC, ThorbenKonopka commented
Hi, bei dem PR fehlt mir, was der Student und der unangemeldete Benutzer tun können. Beide können wahrscheinlich nicht die Anwesenheitsliste  einsehen. Vorsicht: Die einzelnen Fehlzeiten können von dem Studenten eingesehen werden. Wir unterscheiden glaube ich zwischen der Anwesenheitsliste und einzelnen Fehlzeiten. Siehe subsection Fehlzeiten einsehen.

Vielleicht könnte man noch sagen, dass ein Dozent nur die Anwesenheitslisten einsehen bzw. bearbeiten kann, wo er auch für den Termin verantwortlich ist bzw. war.

2024-05-11 07:18 UTC, ThorbenKonopka commented
Was sagts du dazu. @MasterMT9

2024-05-17 17:00 UTC, ThorbenKonopka requested changes

2024-05-17 17:00 UTC, ThorbenKonopka commented on Anforderungsdokument/FunktionaleAnforderungen.tex
> +	\printfreqnr
```suggestion
```

2024-05-18 09:03 UTC, meierlqrITC approved these changes

2024-05-18 11:25 UTC, MasterMT9 commented
@ThorbenKonopka habe die Zeilen entfernt

2024-05-18 12:01 UTC, ThorbenKonopka commented
Bitte noch Veranstaltung durch Termin ersetzen. :)

2024-05-18 12:37 UTC, ThorbenKonopka approved these changes

2024-05-18 12:56 UTC, merged