Anforderungen an Termine verschieben ergänzt
ThorbenKonopka/Stundenplan pull request #51
Opened 2024-05-16 16:02 UTC by johep-ITC

Issue #43

2024-05-17 16:51 UTC, ThorbenKonopka requested changes

2024-05-17 16:51 UTC, ThorbenKonopka commented on Anforderungsdokument/FunktionaleAnforderungen.tex
> +	& Ein Dozent \textbf{KÖNNTE} eine Vorschau von ausstehenden Anfragen in seiner Terminansicht haben. Dabei sollte der ursprüngliche Termin als vorläufig nicht mehr aktuell gekennzeichnet werden.
```suggestion
	& Ein Dozent \textbf{SOLL} eine Vorschau von ausstehenden Anfragen in seiner Terminansicht haben. Dabei sollte der ursprüngliche Termin als vorläufig nicht mehr aktuell gekennzeichnet werden.
```

2024-05-18 07:41 UTC, johep-ITC commented on Anforderungsdokument/FunktionaleAnforderungen.tex
> +	& Ein Dozent \textbf{KÖNNTE} eine Vorschau von ausstehenden Anfragen in seiner Terminansicht haben. Dabei sollte der ursprüngliche Termin als vorläufig nicht mehr aktuell gekennzeichnet werden.
Ist angepasst

2024-05-18 07:51 UTC, ThorbenKonopka approved these changes

2024-05-18 09:03 UTC, meierlqrITC approved these changes

2024-05-18 12:09 UTC, merged